POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "enriquerodridel@gmail.com",
    "password": "1234asdf"
}

###
PUT http://localhost:5000/auth/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UzZGRiOTFlMjZjNmZjNjlhZTNjNzEiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyOTg2NjgxLCJleHAiOjE3NDMwMjI2ODF9.5_pHL0FbJxu4EAbHFVJiel6wyxoMPyUMBN8mOMX5exI

{
    "code": "917744"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "enriquerodridel@gmail.com",
    "password": "1234asdf"
}

###
PATCH http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2QyOTc3ZTc4YTM2Y2U5N2U5YjQ2NDQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQxODU3NTc2LCJleHAiOjE3NDE4OTM1NzZ9.6VQ0DgbVJMa4sHaVZouuHtKEwe7gDDT6saUMbi7_LA4

{
    "name": "test3",
    "surnames": "test3Surname",
    "nif": "12345678Z"
}

###
POST http://localhost:5000/mail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UzZGMyOTg0ODA5OWY4MTY4MjRlOTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyOTg2MzM2LCJleHAiOjE3NDMwMjIzMzZ9.H9fQJ3aK0c7rnSfKvBf7I9eAka7Vn4bNH_6x5oi1I8g

{
    "subject": "Test",
    "text": "Test message",
    "to": "enriquerodridel@gmail.com",
    "from": "no-reply@rodriguezdelreal.com"

}